"""Initial Migration

Revision ID: 30ec997f0691
Revises: 
Create Date: 2024-05-22 17:42:03.464811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ec997f0691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('casper_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=10), nullable=False),
    sa.Column('station', sa.String(length=50), nullable=False),
    sa.Column('station_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('casper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['casper_id'], ['casper.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment')
    op.drop_table('station')
    op.drop_table('casper')
    # ### end Alembic commands ###
