"""initial migration

Revision ID: e311693bafeb
Revises: 
Create Date: 2024-06-04 18:59:37.658099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e311693bafeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('casper_id', sa.String(length=10), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('casper_id')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=10), nullable=False),
    sa.Column('station', sa.String(length=50), nullable=False),
    sa.Column('station_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('casper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['casper_id'], ['casper.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('casper_id', sa.Integer(), nullable=False),
    sa.Column('primary_scan', sa.Integer(), nullable=True),
    sa.Column('secondary_scan', sa.Integer(), nullable=True),
    sa.Column('bagging_scan', sa.Integer(), nullable=True),
    sa.Column('sl_scan', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['casper_id'], ['casper.casper_id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_data')
    op.drop_table('deployment')
    op.drop_table('station')
    op.drop_table('casper')
    # ### end Alembic commands ###
